name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run checks
      run: make check

    - name: Run distcheck
      run: make distcheck
